from __future__ import annotations

from pathlib import Path
from typing import Dict, List, Tuple

import networkx as nx
import numpy as np
import plotly.graph_objects as go
from sklearn.decomposition import PCA


class VisualizationError(RuntimeError):
    """Raised when hypercube visualization cannot be generated."""


def generate_hypercube_vertices_and_edges(n: int = 4) -> Tuple[np.ndarray, List[Tuple[int, int]], List[str]]:
    """Generate n-bit hypercube vertices and Hamming-distance-1 edges.

    This function is optimized with bit operations:
    - vertices are generated by integer bit expansion
    - edges are generated by flipping one bit with XOR
    """
    if not isinstance(n, int):
        raise VisualizationError("n must be an integer.")
    if n < 2 or n > 4:
        raise VisualizationError("n must satisfy 2 <= n <= 4 for 3D PCA visualization.")

    vertex_count = 1 << n
    ids = np.arange(vertex_count, dtype=np.uint32)
    bit_positions = np.arange(n - 1, -1, -1, dtype=np.uint32)
    vertices = ((ids[:, None] >> bit_positions) & 1).astype(np.float64)
    labels = [format(i, f"0{n}b") for i in range(vertex_count)]

    edges: List[Tuple[int, int]] = []
    for i in range(vertex_count):
        for bit in range(n):
            j = i ^ (1 << bit)
            if i < j:
                edges.append((i, j))

    return vertices, edges, labels


def visualize_hypercube(
    n: int = 4,
    *,
    output_html: str = "plots/hypercube_plotly_pca.html",
) -> Dict[str, object]:
    """Visualize an n-bit hypercube using PCA(3) and Plotly 3D rendering.

    Steps implemented:
    1) Generate n-dimensional binary vertices and Hamming-distance-1 edges.
    2) Project vertices to 3D using sklearn PCA with 3 components.
    3) Build interactive Plotly Scatter3d nodes and edges.

    Returns metadata and output artifact path for agentic workflows.
    """
    vertices_nd, edges, labels = generate_hypercube_vertices_and_edges(n=n)

    # PCA(3) requires at least 3 input features; for n=2, pad one zero-feature.
    vertices_for_pca = vertices_nd
    if vertices_for_pca.shape[1] < 3:
        pad = 3 - vertices_for_pca.shape[1]
        vertices_for_pca = np.pad(vertices_for_pca, ((0, 0), (0, pad)), mode="constant")

    pca = PCA(n_components=3)
    coords_3d = pca.fit_transform(vertices_for_pca)

    node_x = coords_3d[:, 0]
    node_y = coords_3d[:, 1]
    node_z = coords_3d[:, 2]

    edge_x: List[float] = []
    edge_y: List[float] = []
    edge_z: List[float] = []
    for i, j in edges:
        edge_x += [float(node_x[i]), float(node_x[j]), None]
        edge_y += [float(node_y[i]), float(node_y[j]), None]
        edge_z += [float(node_z[i]), float(node_z[j]), None]

    edge_trace = go.Scatter3d(
        x=edge_x,
        y=edge_y,
        z=edge_z,
        mode="lines",
        line=dict(width=3, color="#1f77b4"),
        hoverinfo="none",
        name="edges",
    )

    node_trace = go.Scatter3d(
        x=node_x,
        y=node_y,
        z=node_z,
        mode="markers",
        marker=dict(size=7, color="#d62728", opacity=0.95),
        text=labels,
        hovertemplate="vertex=%{text}<extra></extra>",
        name="vertices",
    )

    fig = go.Figure(data=[edge_trace, node_trace])
    fig.update_layout(
        title=f"{n}-Bit Hypercube (PCA to 3D)",
        showlegend=False,
        margin=dict(l=0, r=0, b=0, t=40),
        scene=dict(
            xaxis=dict(visible=False, showgrid=False, zeroline=False, showbackground=False),
            yaxis=dict(visible=False, showgrid=False, zeroline=False, showbackground=False),
            zaxis=dict(visible=False, showgrid=False, zeroline=False, showbackground=False),
            bgcolor="rgba(0,0,0,0)",
        ),
        paper_bgcolor="white",
        plot_bgcolor="white",
    )

    out_path = Path(output_html)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.write_html(str(out_path), include_plotlyjs="cdn")

    return {
        "n": n,
        "vertex_count": int(vertices_nd.shape[0]),
        "edge_count": int(len(edges)),
        "pca_explained_variance_ratio": pca.explained_variance_ratio_.tolist(),
        "html_path": str(out_path.resolve()),
    }


def _projection_matrix_from_mapping(projection: Dict[str, np.ndarray], labels: list[str]) -> np.ndarray:
    try:
        return np.array([projection[label] for label in labels], dtype=float)
    except KeyError as exc:
        raise VisualizationError(
            f"Projection mapping is missing node label: {exc.args[0]}"
        ) from exc


def save_hypercube_plots(
    graph: nx.Graph,
    projection: Dict[str, np.ndarray],
    *,
    output_dir: str = "plots",
    base_filename: str = "hypercube_projection",
    max_plot_nodes: int = 512,
    seed: int = 42,
) -> Dict[str, str | int | bool]:
    """Save static SVG and interactive HTML 3D hypercube plots.

    Args:
        graph: Graph containing hypercube edges.
        projection: Mapping of node label to 3D coordinates.
        output_dir: Directory where plot artifacts are saved.
        base_filename: Base file stem used for output files.

    Returns:
        Dictionary with keys svg_path, html_path and sampling metadata.

    Raises:
        VisualizationError: If plotting fails.
    """
    if not isinstance(graph, nx.Graph):
        raise VisualizationError("graph must be a networkx.Graph instance.")
    if not projection:
        raise VisualizationError("projection is empty; project vertices before plotting.")

    if max_plot_nodes <= 0:
        raise VisualizationError("max_plot_nodes must be positive.")

    all_labels = list(graph.nodes())
    sampled = len(all_labels) > max_plot_nodes
    if sampled:
        rng = np.random.default_rng(seed)
        selected_indices = rng.choice(len(all_labels), size=max_plot_nodes, replace=False)
        selected_indices.sort()
        labels = [all_labels[idx] for idx in selected_indices]
        graph_to_plot = graph.subgraph(labels).copy()
    else:
        labels = all_labels
        graph_to_plot = graph

    points = _projection_matrix_from_mapping(projection, labels)

    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    svg_path = output_path / f"{base_filename}.svg"
    html_path = output_path / f"{base_filename}.html"

    # Create a simple static SVG by orthographically projecting (x, y, z) -> (x, y)
    # and encoding depth as marker size.
    xy = points[:, :2]
    z = points[:, 2]
    min_xy = xy.min(axis=0)
    max_xy = xy.max(axis=0)
    span_xy = np.maximum(max_xy - min_xy, 1e-8)
    normalized = (xy - min_xy) / span_xy

    width = 1000
    height = 800
    padding = 70
    sx = padding + normalized[:, 0] * (width - 2 * padding)
    sy = padding + (1.0 - normalized[:, 1]) * (height - 2 * padding)

    z_norm = (z - z.min()) / max(z.max() - z.min(), 1e-8)
    radius = 3.5 + 4.5 * z_norm

    edge_lines = []
    index_by_label = {label: idx for idx, label in enumerate(labels)}
    for u, v in graph_to_plot.edges():
        i = index_by_label[u]
        j = index_by_label[v]
        edge_lines.append(
            f'<line x1="{sx[i]:.2f}" y1="{sy[i]:.2f}" x2="{sx[j]:.2f}" y2="{sy[j]:.2f}" '
            'stroke="#1f77b4" stroke-opacity="0.55" stroke-width="1.2" />'
        )

    node_circles = []
    node_labels = []
    for idx, label in enumerate(labels):
        node_circles.append(
            f'<circle cx="{sx[idx]:.2f}" cy="{sy[idx]:.2f}" r="{radius[idx]:.2f}" fill="#d62728" />'
        )
        node_labels.append(
            f'<text x="{sx[idx] + 5:.2f}" y="{sy[idx] - 5:.2f}" '
            'font-size="10" fill="#111">'
            f"{label}</text>"
        )

    svg_content = (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" '
        'viewBox="0 0 1000 800">'
        '<rect x="0" y="0" width="1000" height="800" fill="#f7f7fa" />'
        '<text x="30" y="40" font-size="24" fill="#111">Hypercube Projection (Static SVG)</text>'
        + "".join(edge_lines)
        + "".join(node_circles)
        + "".join(node_labels)
        + "</svg>"
    )

    try:
        svg_path.write_text(svg_content, encoding="utf-8")
    except Exception as exc:
        raise VisualizationError(f"Failed to save SVG plot: {exc}") from exc

    points_js = ",\n".join(
        [
            '{label: "' + label + '", x: ' + f"{coord[0]:.8f}" + ', y: ' + f"{coord[1]:.8f}" + ', z: ' + f"{coord[2]:.8f}" + "}"
            for label, coord in projection.items()
        ]
    )
    edges_js = ",\n".join([f'["{u}", "{v}"]' for u, v in graph_to_plot.edges()])

    html_content = f"""<!doctype html>
<html lang=\"en\">
<head>
  <meta charset=\"utf-8\" />
  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />
  <title>Hypercube Interactive Plot</title>
  <style>
    body {{ margin: 0; font-family: Segoe UI, sans-serif; background: #f3f4f8; color: #111; }}
    .wrap {{ max-width: 1100px; margin: 0 auto; padding: 16px; }}
    h1 {{ margin: 0 0 12px 0; font-size: 22px; }}
    .controls {{ display: flex; gap: 16px; align-items: center; margin-bottom: 12px; }}
    #view {{ background: white; border: 1px solid #d0d0d8; border-radius: 12px; width: 100%; height: 72vh; }}
    .small {{ color: #444; font-size: 13px; }}
  </style>
</head>
<body>
  <div class=\"wrap\">
    <h1>Hypercube Interactive Projection</h1>
    <div class=\"controls\">
      <label>Rotate Y: <input id=\"ry\" type=\"range\" min=\"-180\" max=\"180\" value=\"25\" /></label>
      <label>Rotate X: <input id=\"rx\" type=\"range\" min=\"-180\" max=\"180\" value=\"20\" /></label>
      <span class=\"small\">Drag sliders to inspect structure.</span>
    </div>
    <canvas id=\"view\" width=\"1200\" height=\"780\"></canvas>
  </div>
  <script>
    const points = [{points_js}];
    const edges = [{edges_js}];
    const byLabel = new Map(points.map(p => [p.label, p]));
    const canvas = document.getElementById('view');
    const ctx = canvas.getContext('2d');
    const rx = document.getElementById('rx');
    const ry = document.getElementById('ry');

    function rotate(p, ax, ay) {{
      const cx = Math.cos(ax), sx = Math.sin(ax);
      const cy = Math.cos(ay), sy = Math.sin(ay);
      let x = p.x, y = p.y, z = p.z;
      const y1 = y * cx - z * sx;
      const z1 = y * sx + z * cx;
      const x2 = x * cy + z1 * sy;
      const z2 = -x * sy + z1 * cy;
      return {{x: x2, y: y1, z: z2, label: p.label}};
    }}

    function project(p) {{
      const scale = 230;
      const d = 3.2;
      const f = d / (d - p.z * 0.6);
      return {{
        x: canvas.width / 2 + p.x * scale * f,
        y: canvas.height / 2 - p.y * scale * f,
        r: Math.max(2.5, 4 * f)
      }};
    }}

    function draw() {{
      const ax = Number(rx.value) * Math.PI / 180;
      const ay = Number(ry.value) * Math.PI / 180;
      const transformed = points.map(p => rotate(p, ax, ay));
      const tByLabel = new Map(transformed.map(p => [p.label, p]));

      ctx.clearRect(0, 0, canvas.width, canvas.height);
      ctx.fillStyle = '#ffffff';
      ctx.fillRect(0, 0, canvas.width, canvas.height);

      ctx.strokeStyle = 'rgba(31,119,180,0.45)';
      ctx.lineWidth = 1.4;
      for (const [a, b] of edges) {{
        const pa = project(tByLabel.get(a));
        const pb = project(tByLabel.get(b));
        ctx.beginPath();
        ctx.moveTo(pa.x, pa.y);
        ctx.lineTo(pb.x, pb.y);
        ctx.stroke();
      }}

      transformed.sort((a, b) => a.z - b.z);
      for (const p of transformed) {{
        const q = project(p);
        ctx.fillStyle = '#d62728';
        ctx.beginPath();
        ctx.arc(q.x, q.y, q.r, 0, Math.PI * 2);
        ctx.fill();

        ctx.fillStyle = '#111';
        ctx.font = '12px Segoe UI';
        ctx.fillText(p.label, q.x + 6, q.y - 6);
      }}
    }}

    rx.addEventListener('input', draw);
    ry.addEventListener('input', draw);
    draw();
  </script>
</body>
</html>"""

    try:
        html_path.write_text(html_content, encoding="utf-8")
    except Exception as exc:
        raise VisualizationError(f"Failed to save HTML plot: {exc}") from exc

    return {
        "svg_path": str(svg_path.resolve()),
        "html_path": str(html_path.resolve()),
        "sampled": sampled,
        "plotted_nodes": graph_to_plot.number_of_nodes(),
        "plotted_edges": graph_to_plot.number_of_edges(),
    }
